//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMMClient.RMMDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RMMDataService.IRagialPoller", CallbackContract=typeof(RMMClient.RMMDataService.IRagialPollerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRagialPoller {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRagialPoller/RegisterObserver")]
        void RegisterObserver(string itemName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRagialPoller/UnregisterObserver")]
        void UnregisterObserver(string itemName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRagialPoller/SetTargetServer")]
        void SetTargetServer(string serverName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRagialPollerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRagialPoller/ClientUpdate")]
        void ClientUpdate(System.IO.MemoryStream pushData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRagialPoller/ClientErrorMessage")]
        void ClientErrorMessage(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRagialPollerChannel : RMMClient.RMMDataService.IRagialPoller, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RagialPollerClient : System.ServiceModel.DuplexClientBase<RMMClient.RMMDataService.IRagialPoller>, RMMClient.RMMDataService.IRagialPoller {
        
        public RagialPollerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RagialPollerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RagialPollerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RagialPollerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RagialPollerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterObserver(string itemName) {
            base.Channel.RegisterObserver(itemName);
        }
        
        public void UnregisterObserver(string itemName) {
            base.Channel.UnregisterObserver(itemName);
        }
        
        public void SetTargetServer(string serverName) {
            base.Channel.SetTargetServer(serverName);
        }
    }
}
